name: Install/Upgrade on Civo

on:
  repository_dispatch:
    types: [install_civo]
  workflow_dispatch: 

jobs:
  install_civo:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.15.0'    
      id: install
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1
    - name: Install civo
      uses: civo/action-civo
      with:
        token: ${{ secrets.CIVO_TOKEN }}
    - name: Save Civo kubeconfig
      run: civo kubernetes config CLUSTER_NAME
    - name: Print payload
      env:
        MESSAGE: ${{ github.event.client_payload.message }}
      run: echo $MESSAGE

    - name: Install jq
      run: sudo apt-get install jq

    - name: Add Helm repo
      run: helm repo add unoplat-service-mesh https://unoplat.github.io/unoplat-service-mesh

    - name: Update Helm repo
      run: helm repo update

    - name: Install latest pre-release version
      run: |
        version=$(helm search repo unoplat-service-mesh/consul --versions --devel --output json | jq -r '.[0].version')
        helm upgrade --install unoplat-consul-release --namespace unoplat-service-mesh unoplat-service-mesh/consul --version $version --devel --create-namespace