name: Merge with develop branch

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:  

jobs:
  dev-pr-merge:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v2
      with:
        ref: develop
        fetch-depth: 0 

    
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"  
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Install yq
      run: |
        sudo snap install yq

# Not required as of now
    # - name: set version with dev
    #   run: |
    #     yq eval '.version = "dev-" + .version' charts/Chart.yaml -i

    - name: Add Changed Files to Git
      run: |
        git add charts/Chart.yaml

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: charts
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      

        
