name: Merge with develop branch

on:
  pull_request:
    types: [closed]
    branches:
      - develop
  workflow_dispatch:  

jobs:
  dev-pr-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.1

    - name: Install yq
      run: |
        sudo snap install yq


    - name: set version with dev
      run: |
        yq eval '.version = "dev-" + .version' charts/Chart.yaml -i

    - name: Publish Helm charts
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: charts   

       

      

        
